INSERT INTO Countries VALUES ('Afghanistan', 'AF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Åland Islands', 'AX') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Albania', 'AL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Algeria', 'DZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('American Samoa', 'AS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Andorra', 'AD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Angola', 'AO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Anguilla', 'AI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Antarctica', 'AQ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Antigua and Barbuda', 'AG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Argentina', 'AR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Armenia', 'AM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Aruba', 'AW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Australia', 'AU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Austria', 'AT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Azerbaijan', 'AZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bahamas', 'BS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bahrain', 'BH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bangladesh', 'BD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Barbados', 'BB') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Belarus', 'BY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Belgium', 'BE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Belize', 'BZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Benin', 'BJ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bermuda', 'BM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bhutan', 'BT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bolivia', 'BO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bosnia and Herzegovina', 'BA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Botswana', 'BW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bouvet Island', 'BV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Brazil', 'BR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('British Indian Ocean Territory', 'IO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Brunei Darussalam', 'BN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Bulgaria', 'BG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Burkina Faso', 'BF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Burundi', 'BI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cambodia', 'KH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cameroon', 'CM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Canada', 'CA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cape Verde', 'CV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cayman Islands', 'KY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Central African Republic', 'CF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Chad', 'TD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Chile', 'CL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('China', 'CN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Christmas Island', 'CX') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cocos (Keeling) Islands', 'CC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Colombia', 'CO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Comoros', 'KM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Congo', 'CG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Congo, the Democratic Republic of the', 'CD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cook Islands', 'CK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Costa Rica', 'CR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Côte d''Ivoire', 'CI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Croatia', 'HR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cuba', 'CU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Cyprus', 'CY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Czech Republic', 'CZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Denmark', 'DK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Djibouti', 'DJ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Dominica', 'DM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Dominican Republic', 'DO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Ecuador', 'EC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Egypt', 'EG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('El Salvador', 'SV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Equatorial Guinea', 'GQ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Eritrea', 'ER') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Estonia', 'EE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Ethiopia', 'ET') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Falkland Islands (Malvinas)', 'FK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Faroe Islands', 'FO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Fiji', 'FJ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Finland', 'FI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('France', 'FR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('French Guiana', 'GF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('French Polynesia', 'PF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('French Southern Territories', 'TF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Gabon', 'GA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Gambia', 'GM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Georgia', 'GE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Germany', 'DE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Ghana', 'GH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Gibraltar', 'GI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Greece', 'GR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Greenland', 'GL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Grenada', 'GD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guadeloupe', 'GP') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guam', 'GU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guatemala', 'GT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guernsey', 'GG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guinea', 'GN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guinea-Bissau', 'GW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Guyana', 'GY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Haiti', 'HT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Heard Island and McDonald Islands', 'HM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Holy See (Vatican City State)', 'VA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Honduras', 'HN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Hong Kong', 'HK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Hungary', 'HU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Iceland', 'IS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('India', 'IN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Indonesia', 'ID') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Iran', 'IR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Iraq', 'IQ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Ireland', 'IE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Isle of Man', 'IM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Israel', 'IL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Italy', 'IT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Jamaica', 'JM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Japan', 'JP') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Jersey', 'JE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Jordan', 'JO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Kazakhstan', 'KZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Kenya', 'KE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Kiribati', 'KI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Korea, Democratic People''s Republic of', 'KP') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Korea, Republic of (South Korea)', 'KR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Kuwait', 'KW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Kyrgyzstan', 'KG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Lao People''s Democratic Republic', 'LA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Latvia', 'LV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Lebanon', 'LB') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Lesotho', 'LS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Liberia', 'LR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Libyan Arab Jamahiriya', 'LY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Liechtenstein', 'LI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Lithuania', 'LT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Luxembourg', 'LU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Macao', 'MO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Macedonia, the former Yugoslav Republic of', 'MK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Madagascar', 'MG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Malawi', 'MW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Malaysia', 'MY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Maldives', 'MV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mali', 'ML') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Malta', 'MT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Marshall Islands', 'MH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Martinique', 'MQ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mauritania', 'MR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mauritius', 'MU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mayotte', 'YT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mexico', 'MX') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Micronesia, Federated States of', 'FM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Moldova, Republic of', 'MD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Monaco', 'MC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mongolia', 'MN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Montenegro', 'ME') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Montserrat', 'MS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Morocco', 'MA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Mozambique', 'MZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Myanmar', 'MM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Namibia', 'NA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Nauru', 'NR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Nepal', 'NP') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Netherlands', 'NL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Netherlands Antilles', 'AN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('New Caledonia', 'NC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('New Zealand', 'NZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Nicaragua', 'NI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Niger', 'NE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Nigeria', 'NG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Niue', 'NU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Norfolk Island', 'NF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Northern Mariana Islands', 'MP') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Norway', 'NO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Oman', 'OM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Pakistan', 'PK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Palau', 'PW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Palestinian Territory, Occupied', 'PS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Panama', 'PA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Papua New Guinea', 'PG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Paraguay', 'PY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Peru', 'PE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Philippines', 'PH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Pitcairn', 'PN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Poland', 'PL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Portugal', 'PT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Puerto Rico', 'PR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Qatar', 'QA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Reunion', 'RE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Romania', 'RO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Russia', 'RU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Rwanda', 'RW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Barthélemy', 'BL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Helena, Ascension and Tristan da Cunha', 'SH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Kitts and Nevis', 'KN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Lucia', 'LC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Martin', 'MF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Pierre and Miquelon', 'PM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saint Vincent and the Grenadines', 'VC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Samoa', 'WS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('San Marino', 'SM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Sao Tome and Principe', 'ST') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Saudi Arabia', 'SA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Senegal', 'SN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Serbia', 'RS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Seychelles', 'SC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Sierra Leone', 'SL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Singapore', 'SG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Slovakia', 'SK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Slovenia', 'SI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Solomon Islands', 'SB') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Somalia', 'SO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('South Africa', 'ZA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('South Georgia and the South Sandwich Islands', 'GS') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Spain', 'ES') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Sri Lanka', 'LK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Sudan', 'SD') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Suriname', 'SR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Svalbard and Jan Mayen', 'SJ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Swaziland', 'SZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Sweden', 'SE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Switzerland', 'CH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Syrian Arab Republic', 'SY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Taiwan', 'TW') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tajikistan', 'TJ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tanzania, United Republic of', 'TZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Thailand', 'TH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Timor-Leste', 'TL') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Togo', 'TG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tokelau', 'TK') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tonga', 'TO') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Trinidad and Tobago', 'TT') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tunisia', 'TN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Turkey', 'TR') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Turkmenistan', 'TM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Turks and Caicos', 'TC') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Tuvalu', 'TV') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Uganda', 'UG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Ukraine', 'UA') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('United Arab Emirates', 'AE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('United Kingdom', 'GB') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('United States Of America', 'US') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('United States Minor Outlying Islands', 'UM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Uruguay', 'UY') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Uzbekistan', 'UZ') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Vanuatu', 'VU') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Venezuela', 'VE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Vietnam', 'VN') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Virgin Islands, British', 'VG') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Virgin Islands, U.S.', 'VI') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Wallis and Futuna', 'WF') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Western Sahara', 'EH') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Yemen', 'YE') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Zambia', 'ZM') ON CONFLICT (CountryCode) DO NOTHING;
INSERT INTO Countries VALUES ('Zimbabwe', 'ZW') ON CONFLICT (CountryCode) DO NOTHING;
