-- added the on conflict for the primary key so it doesn't bug out when we try to re-insert later
INSERT INTO Journals VALUES ('CA-A CANCER JOURNAL FOR CLINICIANS', 'CA-CANCER J CLIN', 'WILEY', '0007-9235', '1542-4863', 'ONCOLOGY', 'SCIE', '232.4') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('NATURE REVIEWS MICROBIOLOGY', 'NAT REV MICROBIOL', 'NATURE PORTFOLIO', '1740-1526', '1740-1534', 'MICROBIOLOGY', 'SCIE', '103.3') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('NATURE REVIEWS DRUG DISCOVERY', 'NAT REV DRUG DISCOV', 'NATURE PORTFOLIO', '1474-1776', '1474-1784', 'PHARMACOLOGY & PHARMACY', 'SCIE', '101.8') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('NATURE REVIEWS MOLECULAR CELL BIOLOGY', 'NAT REV MOL CELL BIO', 'NATURE PORTFOLIO', '1471-0072', '1471-0080', 'CELL BIOLOGY', 'SCIE', '90.2') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('Kidney International Supplements', 'KIDNEY INT SUPPL', 'ELSEVIER SCIENCE INC', '2157-1724', '2157-1716', 'UROLOGY & NEPHROLOGY', 'SCIE', '89.6') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('LANCET', 'LANCET', 'ELSEVIER SCIENCE INC', '0140-6736', '1474-547X', 'MEDICINE, GENERAL & INTERNAL', 'SCIE', '88.5') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('Nature Reviews Materials', 'NAT REV MATER', 'NATURE PORTFOLIO', '2058-8437', '2058-8437', 'NANOSCIENCE & NANOTECHNOLOGY', 'SCIE', '87.2') ON CONFLICT (LongName) DO NOTHING;
INSERT INTO Journals VALUES ('Nature Reviews Clinical Oncology', 'NAT REV CLIN ONCOL', 'NATURE PORTFOLIO', '1759-4774', '1759-4782', 'ONCOLOGY', 'SCIE', '83.2') ON CONFLICT (LongName) DO NOTHING;
